name: service-docker-compose-generator
namespace: platform

environment:
  _:
    HTTP_API_PORT: 9000
    GRPC_API_PORT: 9001

    JAEGER_SERVICE_NAME: service-docker-compose-generator
    JAEGER_SAMPLER_TYPE: const
    JAEGER_SAMPLER_PARAM: 1
  local:
    JAEGER_ENDPOINT: http://localhost:14268/api/traces
  staging: ~
