version: '3'

tasks:
  platformctl:build:
    desc: Build platformctl binary
    dir: platformctl
    cmds:
      - go build -o bin/platformctl cmd/platformctl/main.go

  doc:run:
    desc: Run documentation locally
    dir: platform-doc
    cmds:
      - |
        NERDCTL=$(command -v nerdctl)
        DOCKER=$(command -v docker)
        ${NERDCTL:-$DOCKER} run \
          --pull always \
          --rm \
          -p 8000:8000 \
          -v ${PWD}:/docs \
          squidfunk/mkdocs-material serve --dev-addr=0.0.0.0:8000 --watch-theme

  platform-image:task:all:build:
    desc: Build all platform/task images
    cmds:
      - task: platform-image:task:directory-lister:build
      - task: platform-image:task:golangci-lint:build
      - task: platform-image:task:golang-migrate:build

  platform-image:task:directory-lister:build:
    desc: Build platform/directory-lister image
    dir: platform-image/task/directory-lister
    cmds:
      - docker build --tag platform/task/directory-lister .

  platform-image:task:golangci-lint:build:
    desc: Build platform/golangci-lint image
    dir: platform-image/task/golangci-lint
    cmds:
      - docker build --tag platform/task/golangci-lint .

  platform-image:task:golang-migrate:build:
    desc: Build platform/golang-migrate image
    dir: platform-image/task/golang-migrate
    cmds:
      - docker build --tag platform/task/golang-migrate .
