version: '3'

tasks:
  platformctl:build:
    desc: Build platformctl binary
    dir: platformctl
    cmds:
      - go build -o bin/platformctl cmd/platformctl/main.go

  doc:run:
    desc: Run documentation locally
    dir: platform-doc
    cmds:
      - |
        docker run \
          --pull always \
          --rm \
          -p 8000:8000 \
          -v ${PWD}:/docs \
          squidfunk/mkdocs-material serve --dev-addr=0.0.0.0:8000 --watch-theme

  platform-image:platform:directory-lister:build:
    desc: Build platform/directory-lister image
    dir: platform-image/platform/directory-lister
    cmds:
      - docker build --tag platform/directory-lister .

  platform-image:platform:golangci-lint:build:
    desc: Build platform/golangci-lint image
    dir: platform-image/platform/golangci-lint
    cmds:
      - docker build --tag platform/golangci-lint .

  platform-image:platform:golang-migrate:build:
    desc: Build platform/golang-migrate image
    dir: platform-image/platform/golang-migrate
    cmds:
      - docker build --tag platform/golang-migrate .
