version: '3'

tasks:
  platformctl:build:
    desc: Build platformctl binary
    dir: platformctl
    cmds:
      - go build -o bin/platformctl cmd/platformctl/main.go

  doc:run:
    desc: Run documentation locally
    dir: platform-doc
    cmds:
      - |
        NERDCTL=$(command -v nerdctl)
        DOCKER=$(command -v docker)
        ${DOCKER:-$NERDCTL} run \
          --pull always \
          --rm \
          -p 8000:8000 \
          -v ${PWD}:/docs \
          squidfunk/mkdocs-material serve --dev-addr=0.0.0.0:8000 --watch-theme

  platform-image:task:all:build:
    desc: Build all platform/task images
    cmds:
      - task: platform-image:task:debugging:directory-lister:build
      - task: platform-image:task:debugging:environ-printer:build
      - task: platform-image:task:golangci-lint:build
      - task: platform-image:task:golang-migrate:build
      - task: platform-image:task:seeder:build
      - task: platform-image:task:gomplate:build

  platform-image:task:debugging:directory-lister:build:
    desc: Build platform/task/debugging/directory-lister image
    dir: platform-image/task/debugging/directory-lister
    cmds:
      - docker build --tag platform/task/debugging/directory-lister .

  platform-image:task:debugging:environ-printer:build:
    desc: Build platform/task/debugging/environ-printer image
    dir: platform-image/task/debugging/environ-printer
    cmds:
      - docker build --tag platform/task/debugging/environ-printer .

  platform-image:task:golangci-lint:build:
    desc: Build platform/task/golangci-lint image
    dir: platform-image/task/golangci-lint
    cmds:
      - docker build --tag platform/task/golangci-lint .

  platform-image:task:golang-migrate:build:
    desc: Build platform/task/golang-migrate image
    dir: platform-image/task/golang-migrate
    cmds:
      - docker build --tag platform/task/golang-migrate .

  platform-image:task:seeder:build:
    desc: Build platform/task/seeder image
    dir: platform-image/task/seeder
    cmds:
      - docker build --tag platform/task/seeder .

  platform-image:task:gomplate:build:
    desc: Build platform/task/gomplate image
    dir: platform-image/task/gomplate
    cmds:
      - docker build --tag platform/task/gomplate .
