version: '3'

tasks:
  platformctl:build:
    desc: Build platformctl binary
    dir: platformctl
    cmds:
      - go build -o bin/platformctl cmd/platformctl/main.go

  doc:run:
    desc: Run documentation locally
    dir: platform-doc
    cmds:
      - |
        docker run \
          --pull always \
          --rm \
          -p 8000:8000 \
          -v ${PWD}:/docs \
          squidfunk/mkdocs-material serve --dev-addr=0.0.0.0:8000 --watch-theme
