---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-start-guide
  namespace: platform
  labels:
    app: quick-start-guide
spec:
  selector:
    matchLabels:
      app: quick-start-guide
  template:
    metadata:
      labels:
        app: quick-start-guide
    spec:
      containers:
        - name: quick-start-guide
          image: platform/quick-start-guide
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: quick-start-guide
  namespace: platform
spec:
  selector:
    app: quick-start-guide
  ports:
    - port: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quick-start-guide
  namespace: platform
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /platform/quick-start-guide(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: quick-start-guide
                port:
                  number: 9000
