platform:
  minikube:
    memory: "4g"
    cpus: "4"
    disk-size: "50g"

go_env_vars:
  - "GONOPROXY=none"
  - "GOPROXY=https://proxy.yourdevdomain.tld"
  - "GONOSUMDB=sumdb.yourdevdomain.tld/*"
  - "GOPRIVATE=*.yourdevdomain.tld"
