site_name: platform
theme:
  name: material
  logo: assets/platform-icon.svg
  palette:
    - scheme: default
      primary: red
      accent: red
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb-outline
        name: Тёмная тема
    - scheme: slate
      primary: grey
      accent: grey
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb
        name: Светлая тема
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.code.annotate
markdown_extensions:
  - footnotes
  - meta
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Документация:
      - Установка и настройка:
          - doc/index.md
          - Установка: doc/getting-started/install.md
          - asdf-vm: doc/getting-started/asdf-vm.md
          - Запуск и остановка: doc/getting-started/start.md
          - Конфигурационный файл: doc/getting-started/cfg-file.md
          - Удаление: doc/getting-started/delete.md
      - Список команд: doc/command-list/index.md
      - Манифест сервиса: doc/service-manifest.md
  - Туториалы:
      - tutorial/index.md
      - Работа в локальном окружении:
          - Запуск сервиса в локальном окружении: tutorial/001-service-run-local.md
          - Отладка сервиса в локальном окружении: tutorial/002-service-debug-local.md
  - Разработка:
      - development/index.md
      - Структура проекта: development/project-structure.md
      - Технические заметки: development/technical-notes/index.md
      - Шаблон сервиса: development/service-boilerplate.md
      - Оформление документации: development/doc-design.md
