site_name: platform
theme:
  name: material
  custom_dir: overrides
  logo: asset/platform-icon.svg
  palette:
    - scheme: default
      primary: red
      accent: red
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb-outline
        name: Тёмная тема
    - scheme: slate
      primary: red
      accent: grey
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb
        name: Светлая тема
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.code.annotate
markdown_extensions:
  - footnotes
  - meta
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
nav:
  - В начало: index.md
  - Для разработчиков сервисов:
      - Введение: service-developer/index.md
      - Установка:
          - Установка platformctl: service-developer/install/platformctl.md
          - Установка среды исполнения контейнеров: service-developer/install/container-runtime.md
      - Настройка:
          - Настройка вручную: service-developer/bootstrap/manual.md
      - Список команд:
          - Работа с сервисом: service-developer/command-list/service.md
          - Работа с библиотеками: service-developer/command-list/lib.md
          - Работа с задачами: service-developer/command-list/task.md
          - Библиотека задач: service-developer/command-list/task/index.md
          - Работа с плагинами: service-developer/command-list/plugin.md
      - Работа с сервисами:
          - Манифест сервиса: service-developer/service/manifest.md
          - Создание сервиса: service-developer/service/create.md
          - Запуск сервиса: service-developer/service/run.md
      - Компоненты:
          - Компоненты платформы: service-developer/component/platform.md
          - Компоненты сервиса: service-developer/component/service.md
      - Расширение платформы:
          - Разработка плагинов: service-developer/extension/plugin.md
  - Для разработчиков платформы:
      - Введение: platform-developer/index.md
      - ADR:
          - 1. Record architecture decisions: platform-developer/adr/0001-record-architecture-decisions.md
          - 2. Use Docker Desktop instead of desktop VMs: platform-developer/adr/0002-use-docker-desktop-instead-of-desktop-vms.md
          - 3. Dockerfile is not a part of project repository: platform-developer/adr/0003-dockerfile-is-not-a-part-of-project-repository.md
          - 4. UTC is the only timezone: platform-developer/adr/0004-utc-is-the-only-timezone.md
          - 5. Plugin is a binary: platform-developer/adr/0005-plugin-is-a-binary.md
      - Шаблон сервиса:
          - Требования к шаблону: platform-developer/service-boilerplate/requirement.md
      - Сборка:
          - Сборка образов библиотеки задач: platform-developer/build/platform-image.md
      - План развития:
          - Обратная связь от разработчиков: platform-developer/evolution/feedback-developer.md
          - Обратная связь от devops: platform-developer/evolution/feedback-devops.md
  - Для devops:
      - Введение: devops/index.md
  - Образцовые подходы:
      - Введение: best-practice/index.md
      - Postgres: best-practice/postgres.md
      - Observability: best-practice/observability.md
