site_name: platform
theme:
  name: material
  logo: asset/platform-icon.svg
  palette:
    - scheme: default
      primary: red
      accent: red
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb-outline
        name: Тёмная тема
    - scheme: slate
      primary: red
      accent: grey
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb
        name: Светлая тема
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.code.annotate
markdown_extensions:
  - footnotes
  - meta
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
nav:
  - Для разработчиков сервисов:
      - Введение: service-developer/index.md
      - Установка:
          - Установка platformctl: service-developer/install/platformctl.md
          - Варианты установки: service-developer/install/installation-option.md
      - Настройка:
          - Настройка вручную: service-developer/bootstrap/manual.md
      - Список команд:
          - Работа с сервисом: service-developer/command-list/service.md
          - Работа с библиотеками: service-developer/command-list/lib.md
          - Работа с плагинами: service-developer/command-list/plugin.md
      - Работа с сервисами:
          - Манифест сервиса: service-developer/service/manifest.md
          - Создание сервиса: service-developer/service/create.md
          - Запуск сервиса: service-developer/service/run.md
      - Компоненты:
          - Компоненты платформы: service-developer/component/platform.md
          - Компоненты сервиса: service-developer/component/service.md
      - Расширение платформы:
          - Разработка плагинов: service-developer/extension/plugin.md
  - Для разработчиков платформы:
      - Введение: platform-developer/index.md
      - ADR:
          - 1. Record architecture decisions: platform-developer/adr/0001-record-architecture-decisions.md
          - 2. Use Docker Desktop instead of desktop VMs: platform-developer/adr/0002-use-docker-desktop-instead-of-desktop-vms.md
          - 3. Dockerfile is not a part of project repository: platform-developer/adr/0003-dockerfile-is-not-a-part-of-project-repository.md
          - 4. UTC is the only timezone: platform-developer/adr/0004-utc-is-the-only-timezone.md
          - 5. Plugin is a binary: platform-developer/adr/0005-plugin-is-a-binary.md
  - Для devops:
      - Введение: devops/index.md
  - Образцовые подходы:
      - Postgres: best-practice/postgres.md
      - Observability: best-practice/observability.md

#  - Для devops:
#  - Для разработчиков платформы:
#  - Документация:
#      - Установка и настройка:
#          - doc/index.md
#          - Установка: doc/getting-started/install.md
#          - asdf-vm: doc/getting-started/asdf-vm.md
#          - Запуск и остановка: doc/getting-started/start.md
#          - Конфигурационный файл: doc/getting-started/cfg-file.md
#          - Удаление: doc/getting-started/delete.md
#      - Список команд: doc/command-list/index.md
#      - Манифест сервиса: doc/service-manifest.md
#  - Best Practice:
#      - Observability: best-practice/observability.md
#      - Postgres: best-practice/postgres.md
#  - Туториалы:
#      - tutorial/index.md
#      - Работа в локальном окружении:
#          - Запуск сервиса в локальном окружении: tutorial/001-service-run-local.md
#          - Отладка сервиса в локальном окружении: tutorial/002-service-debug-local.md
#  - Разработка:
#      - development/index.md
#      - Roadmap: development/roadmap.md
#      - Структура проекта: development/project-structure.md
#      - Технические заметки: development/technical-notes/index.md
#      - Матрица фич: development/feature-matrix.md
#      - Шаблон сервиса: development/service-boilerplate.md
#      - Оформление документации: development/doc-design.md
