site_name: platform
theme:
  name: material
  features:
    - toc.integrate
nav:
  - Введение: intro.md
  - Установка и настройка:
      - Установка: getting-started/install.md
      - Запуск и остановка: getting-started/start.md
      - Удаление: getting-started/delete.md
  - Технические заметки: technical-notes/index.md
