site_name: platform
theme:
  name: material
  logo: assets/platform-icon.svg
  features:
    - toc.integrate
markdown_extensions:
  - footnotes
nav:
  - Введение: intro.md
  - Установка и настройка:
      - Установка: getting-started/install.md
      - Запуск и остановка: getting-started/start.md
      - Конфигурационный файл: getting-started/cfg-file.md
      - Удаление: getting-started/delete.md
  - Список команд: command-list/index.md
  - Шаблон сервиса: service-boilerplate.md
  - Технические заметки: technical-notes/index.md
  - Оформление документации: doc-design.md
