#!/usr/bin/env python3

import os
import sys

EXIT_FAILURE = 1
PYTHON_MIN_VERSION_MAJOR = 3
PYTHON_MIN_VERSION_MINOR = 9


def ensure_python_version():
    if not (sys.version_info.major == PYTHON_MIN_VERSION_MAJOR and sys.version_info.minor >= PYTHON_MIN_VERSION_MINOR):
        print("Plugin requires Python {}.{}.".format(PYTHON_MIN_VERSION_MAJOR, PYTHON_MIN_VERSION_MINOR))
        print("Current Python version: {}.{}.".format(sys.version_info.major, sys.version_info.minor))
        sys.exit(EXIT_FAILURE)


def main():
    ensure_python_version()

    print("Hello, I am example python plugin!")
    print("Current PWD:", os.getcwd())
    print("Given args:", sys.argv)


if __name__ == '__main__':
    main()
